# When adding messages be sure to increase the indicating number!
messages: 
  1: 
    "First message"
  2: 
    "&aColorful message!"
  3: 
    "&2Please edit your config.yml. These messages are the default ones!"
  4: 
    "&e&lWhen life gives you lemons, make the MC sun!"
  5: 
    "&8Default message!"
# Customize the delay! This number referrs to SECONDS.
delay: 60